import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { Suspense } from "react";
import { ProgressBar } from "@lexz451/next-nprogress";
import Navbar from "@/components/home/navbar";
import Footer from "@/components/home/footer";
import ThemeEditor from "@/components/home/theme-editor";

export const metadata: Metadata = {
  title: "DyCn Components",
  description: "Generated by Immi",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="customScrollBar dark h-full">
      <body
        className={`flex min-h-full max-w-[100vw] flex-col ${GeistSans.className}`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Suspense fallback={true}>
            <ProgressBar
              height="2px"
              options={{
                showSpinner: false,
              }}
            />
          </Suspense>
          <ThemeEditor />
          <Navbar />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
